// Generated by CoffeeScript 1.6.3
(function() {
  var Search, assert, err;

  assert = require('assert');
  Search = require('../lib/search');

  err = function(data, res) {
    console.log('ERROR');
    console.dir(data);
    return console.dir(res);
  };

  describe('Search', function() {
    return it('should return something for "taylor"', function(done) {
      var s;
      s = new Search('music-hack-day');
      return s.artists('taylor', err, function(data, res) {
        assert(data.length > 0);
        return done();
      });
    });
  });

}).call(this);
