// Generated by CoffeeScript 1.6.3
(function() {
  var Search, async, rest;

  rest = require('restler');

  async = require('async');

  Search = (function() {
    function Search(apiKey, baseUrl, defaultLimit) {
      this.apiKey = apiKey;
      this.baseUrl = baseUrl != null ? baseUrl : "http://api.openaura.com/v1";
      this.defaultLimit = defaultLimit != null ? defaultLimit : 5;
    }

    Search.prototype.artist = function(str, err, cb) {
      var call, uri;
      uri = "" + this.baseUrl + "/search/artists?api_key=" + this.apiKey + "&q=" + str + "&limit=" + this.defaultLimit;
      console.log("req to: " + uri);
      call = rest.get(uri);
      call.on('success', function(data, res) {
        console.log('success');
        return cb(data);
      });
      call.on('fail', function(data, res) {
        console.log('fail', res.statusCode);
        return err(data);
      });
      return call.on('complete', function(data, res) {
        return console.log('complete');
      });
    };

    return Search;

  })();

  module.exports = Search;

}).call(this);
